apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: flex-ds
spec:
  template:
    metadata:
      name: flex-deploy
      labels:
        app: flex-deploy
    spec:
      containers:
        - image: troykinsella/k8s-flexvolume-local
          name: flex-deploy
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /flexmnt
            name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            # TODO Change to the Flexvolume plugin directory of your cluster.
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
